name: ryken_video_player
description: Multiplatform spectacular video player with a good UI/UX
homepage: https://github.com/itskeyy/ryken_video_player
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  gesture_x_detector: ^1.0.0
  helpers: ^1.1.4
  http: ^1.1.0
  path_provider: ^2.0.6
  provider: ^6.0.5
  video_player: ^2.2.6
  volume_watcher: ^2.0.1
  wakelock: ^0.6.2
  video_player_web_hls: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
